//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Type { get; set; }
        public string SubType { get; set; }
        public Nullable<int> BlueMana { get; set; }
        public Nullable<int> GreenMana { get; set; }
        public Nullable<int> WhiteMana { get; set; }
        public Nullable<int> BlackMana { get; set; }
        public Nullable<int> RedMana { get; set; }
        public Nullable<int> NeutralMana { get; set; }
        public int Rarity { get; set; }
        public string Mechanic { get; set; }
        public string CodeName { get; set; }
        public int Power { get; set; }
        public int Defense { get; set; }
        public int EditionId { get; set; }
        public string Commentary { get; set; }
        public string UrlImage { get; set; }
        public bool IsTreated { get; set; }
        public string Skill { get; set; }
    
        public virtual Edition Edition { get; set; }
        public virtual Rarity Rarity1 { get; set; }
        public virtual Type Type1 { get; set; }
    }
}
