//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string Settings { get; set; }
        public string Guid { get; set; }
        public int Edition { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Edition Edition1 { get; set; }
    }
}
